development:
  secret_token: "my_secret_token"
  secret_key_base: "abcdef0123456789"


  # In config/initializers, create file secret_token.rb
  # with Jungle::Application.config.secret_key_base = " Your key from rake secret"